<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function modulename_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Provides the module overview in the help tab.
    case 'help.page.modulename':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';

      $output .= '<p>' . t('This is a template module which should never be
      available on a production site') . '</p>';

      return $output;

    default:
  }
}
