<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_germplasm\Hook\TripalCultivateGermplasmHooks in
 * trpcultivate_germplasm/src/Hook/TripalCultivateGermplasmHooks.php.
 */
#[LegacyHook]
function trpcultivate_germplasm_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate_germplasm.hooks')->help($route_name, $route_match);
}
