<?php

/**
 * @file
 * Provides functionality required for installation of the module.
 */

/**
 * Implements hook_install().
 */
function trpcultivate_germplasm_install() {
  // Submiit a Tripal Job to setup this module.
  $current_user = \Drupal::currentUser();
  \Drupal::service('tripal.job')->create([
    'job_name' => t("Setup Tripal Cultivate Germplasm Module"),
    'modulename' => 'trpcultivate_germplasm',
    'callback' => ['Drupal\trpcultivate_germplasm\Service\SetupModuleService', 'runSetupModuleTripalJob'],
    'arguments' => [],
    'uid' => $current_user->id(),
  ]);
}
