<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_germplasm\Hook\TripalCultivateGermplasmHooks in
 * trpcultivate_germplasm/src/Hook/TripalCultivateGermplasmHooks.php.
 */
#[LegacyHook]
function trpcultivate_germplasm_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate_germplasm.hooks')->help($route_name, $route_match);
}

/**
 * Import ontologies and insert terms needed by this module.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_germplasm_install_terms() {

  $container = \Drupal::getContainer();

  // Insert our config terms (YML file).
  $config_id = 'trpcultivate_germ_terms';
  $container->get('tripal_chado.terms_init')
    ->installTerms($config_id);

  // Insert our ontologies (OBO file).
  $logger = \Drupal::logger('trpcultivate_germplasm');
  $drupal_connection = $container->get('database');
  $schema_name = $container->get('tripal_chado.database')
    ->getSchemaName();

  $obo_importer = $container->get('tripal.importer')
    ->createInstance('chado_obo_loader');

  $ontologies = [
    [
      'name' => 'multicrop passport ontology',
      'path' => '{trpcultivate_germplasm}/ontologies/mcpd_v2.1_151215.obo',
    ],
    [
      'name' => 'Tripal Cultivate Germplasm Ontology',
      'path' => '{trpcultivate_germplasm}/ontologies/TripalCultivateGermplasmOntology.v1.obo',
    ],
  ];

  // Iterate through each ontology and install them with the OBO Importer.
  foreach ($ontologies as $ontology) {
    // Make sure an OBO with the same name doesn't already exist.
    $obo_id = $drupal_connection->select('tripal_cv_obo', 'tco')
      ->fields('tco', ['obo_id'])
      ->condition('name', $ontology['name'])
      ->execute()
      ->fetchField();

    if ($obo_id) {
      $drupal_connection->update('tripal_cv_obo')
        ->fields([
          'path' => $ontology['path'],
        ])
        ->condition('name', $ontology['name'])
        ->execute();
    }
    else {
      $obo_id = $drupal_connection->insert('tripal_cv_obo')
        ->fields([
          'name' => $ontology['name'],
          'path' => $ontology['path'],
        ])
        ->execute();
    }

    if ($obo_id) {
      $logger->notice("Importing " . $ontology['name']);

      $obo_importer->createImportJob(
        [
          'obo_id' => $obo_id,
          'schema_name' => $schema_name,
        ],
        [
          'file_path' => $ontology['path'],
          'file_local' => $ontology['path'],
        ]
      );

      $obo_importer->run();
      $obo_importer->postRun();
    }
    else {
      $logger->error("Tripal Cultivate Germplasm could not insert or find an obo record for ontology " . $ontology['name']);
    }
  }
}
