<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function trpcultivate_germplasm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Provides the module overview in the help tab.
    case 'help.page.trpcultivate_germplasm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';

      $output .= '<p>' . t('This module provides specialized Tripal fields and importers for germplasm.') . '</p>';

      return $output;

    default:
  }
}

/**
 * Import ontologies and insert terms needed by this module.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_germplasm_install_terms() {

  // This is a revised version of the function below. It creates tripal job and
  // installs terms.
  $container = \Drupal::getContainer();
  $tripal_job = $container->get('tripal.job');
  $schema_name = $container->get('tripal_chado.database')
    ->getSchemaName();

  $drupal_connection = $container->get('database');
  $user_id = $container->get('current_user')
    ->id();

  // Insert our config terms (config YML).
  $config_id = 'trpcultivate_germ_terms';
  $container->get('tripal_chado.terms_init')
    ->installTerms($config_id);

  // Insert our OBO terms (OBO file).
  $ontologies = [];
  $ontologies[] = [
    'name' => 'Multi-Crop Passport Ontology',
    'path' => '{trpcultivate_germplasm}/ontologies/mcpd_v2.1_151215.obo',
  ];
  $ontologies[] = [
    'name' => 'TripalCultivate Germplasm Ontology',
    'path' => '{trpcultivate_germplasm}/ontologies/TripalCultivateGermplasmOntology.v1.obo',
  ];

  // Iterate through each ontology and install them with the OBO Importer.
  foreach ($ontologies as $ontology) {
    // Make sure an OBO with the same name doesn't already exist.
    $obo_id = $drupal_connection->select('tripal_cv_obo', 'tco')
      ->fields('tco', ['obo_id'])
      ->condition('name', $ontology['name'])
      ->execute()
      ->fetchField();

    if ($obo_id) {
      $drupal_connection->update('tripal_cv_obo')
        ->fields([
          'path' => $ontology['path'],
        ])
        ->condition('name', $ontology['name'])
        ->execute();
    }
    else {
      $obo_id = $drupal_connection->insert('tripal_cv_obo')
        ->fields([
          'name' => $ontology['name'],
          'path' => $ontology['path'],
        ])
        ->execute();
    }

    $import_id = $drupal_connection->insert('tripal_import')
      ->fields(
      [
        'uid' => $user_id,
        'class' => 'chado_obo_loader',
        'submit_date' => time(),
        'arguments' => base64_encode(serialize([
          'run_args' => [
            'obo_id' => $obo_id,
            'schema_name' => $schema_name,
          ],
          'files' => [
            'file_local' => $ontology['path'],
            'file_path' => $ontology['path'],
          ],
        ])),
      ]
    )
      ->execute();

    $tripal_job->create([
      'job_name' => 'Insert TripalCultivate Germplasm Terms: OBO - ' . $ontology['name'],
      'modulename' => 'trpcultivate_germplasm',
      'callback' => 'tripal_run_importer',
      'arguments' => [$import_id],
      'uid' => $user_id,
    ]);

    $tripal_job->run();
  }
}

/**
 * Import ontologies and insert terms needed by this module.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_germplasm_install_terms_original() {

  // This is the original code. This does not setup a tripal job nor
  // create terms.
  // To test this: replace the function call in hook_install() (.install file)
  // to reference this function name.
  // Insert our terms.
  $config_id = 'trpcultivate_germ_terms';
  $terms_setup = \Drupal::service('tripal_chado.terms_init');
  $terms_setup->installTerms($config_id);

  $schema_name = \Drupal::service('tripal_chado.database')
    ->getSchemaName();

  $drupal_connection = \Drupal::database();

  $ontologies = [];
  $ontologies[] = [
    'name' => 'Multi-Crop Passport Ontology',
    'path' => '{trpcultivate_germplasm}/ontologies/mcpd_v2.1_151215.obo',
  ];
  $ontologies[] = [
    'name' => 'TripalCultivate Germplasm Ontology',
    'path' => '{trpcultivate_germplasm}/ontologies/TripalCultivateGermplasmOntology.v1.obo',
  ];

  // Iterate through each ontology and install them with the OBO Importer.
  foreach ($ontologies as $ontology) {

    // Make sure an OBO with the same name doesn't already exist.
    $obo_id = $drupal_connection->select('tripal_cv_obo', 'tco')
      ->fields('tco', ['obo_id'])
      ->condition('name', $ontology['name'])
      ->execute()
      ->fetchField();

    if ($obo_id) {
      $drupal_connection->update('tripal_cv_obo')
        ->fields([
          'path' => $ontology['path'],
        ])
        ->condition('name', $ontology['name'])
        ->execute();
    }
    else {
      $obo_id = $drupal_connection->insert('tripal_cv_obo')
        ->fields([
          'name' => $ontology['name'],
          'path' => $ontology['path'],
        ])
        ->execute();
    }

    if ($obo_id) {
      \Drupal::logger('trpcultivate_germplasm')->notice("Importing " . $ontology['name']);
      $importer_manager = \Drupal::service('tripal.importer');
      $obo_importer = $importer_manager->createInstance('chado_obo_loader');
      $obo_importer->createImportJob(['obo_id' => $obo_id, 'schema_name' => $schema_name]);
      $obo_importer->run();
      $obo_importer->postRun();
    }
    else {
      \Drupal::logger('trpcultivate_germplasm')->error("Tripal Cultivate Germplasm could not insert or find an obo record for ontology " . $ontology['name']);
    }
  }
}
