name: PHPUnit
on:
  push:
    branches:
      - 4.x
      - customize-template
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.1
        with:
          directory-name: 'TripalCultivate-Germplasm'
          modules: 'trpcultivate_germplasm'
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: '8.1'
          pgsql-version: '13'
          drupal-version: '10.1.x-dev'
