name: PHPUnit
on:
  push:
    branches:
      - 4.x
      - g0.34-remove11.0

## UPDATES
## Update the version numbers in the job name and the action parameters
## |  Drupal     |  10.4.x         |  10.5.x         |  11.1.x         | 11.2.x          |
## |-------------|-----------------|-----------------|-----------------|-----------------|
## | **PHP 8.1** | ![Grid1A-Badge] | ![Grid2A-Badge] |                 |                 |
## | **PHP 8.2** | ![Grid1B-Badge] | ![Grid2B-Badge] |                 |                 |
## | **PHP 8.3** | ![Grid1C-Badge] | ![Grid2C-Badge] | ![Grid3C-Badge] | ![Grid4C-Badge] |

jobs:
  grid-4C:
    name: "Drupal 11.2.x-dev - PHP 8.3 - PostgreSQL 16"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.7
        with:
          directory-name: 'TripalCultivate-Germplasm'
          modules: 'trpcultivate_germplasm trpcultivate_germcollection'
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: 8.3
          pgsql-version: 16
          drupal-version: 11.2.x-dev
