name: Build and Publish Docker image
on:
  push:
    branches:
      - 4.x
  # Allows us to manually trigger this workflow.
  # This is great if there is a change made to Tripal core that we want to test our modules on ASAP.
  workflow_dispatch:
  # Allows us to schedule when this workflow is run.
  # This ensures we pick up any new changes committed to Tripal Core.
  schedule:
    # Run at 3am every night.
    - cron: '0 3 * * *'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        pgsql-version:
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
        drupal-version:
          - "10.5.x-dev"
          - "10.6.x-dev"
          - "11.x-dev"
          - "11.2.x-dev"
          - "11.3.x-dev"
        exclude:
          # Only Drupal 11.3+ supports PHP 8.5.
          - php-version: "8.5"
            drupal-version: "10.5.x-dev"
          - php-version: "8.5"
            drupal-version: "10.6.x-dev"
          - php-version: "8.5"
            drupal-version: "11.2.x-dev"
          # Drupal 11.x requires PHP 8.3+.
          - php-version: "8.2"
            drupal-version: "11.x-dev"
          - php-version: "8.2"
            drupal-version: "11.2.x-dev"
          - php-version: "8.2"
            drupal-version: "11.3.x-dev"
          # Drupal 11+ requires at least Postgresql 16.
          - pgsql-version: "14"
            drupal-version: "11.x-dev"
          - pgsql-version: "15"
            drupal-version: "11.x-dev"
          - pgsql-version: "14"
            drupal-version: "11.2.x-dev"
          - pgsql-version: "15"
            drupal-version: "11.2.x-dev"
          - pgsql-version: "14"
            drupal-version: "11.3.x-dev"
          - pgsql-version: "15"
            drupal-version: "11.3.x-dev"
    name: TripalCultivate ${{ matrix.drupal-version }}-php${{ matrix.php-version }}-pgsql${{ matrix.pgsql-version }}
    steps:
      - uses: actions/checkout@v6
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6.5
        name: Build & push Full matrix of Docker images
        with:
          image: knowpulse/tripalcultivate-base
          tags: drupal${{ matrix.drupal-version }}-php${{ matrix.php-version }}-pgsql${{ matrix.pgsql-version }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: "drupalversion=${{ matrix.drupal-version }},phpversion=${{ matrix.php-version }},postgresqlversion=${{ matrix.pgsql-version }}"
          labels: 'drupal.version.label="${{ matrix.drupal-version }}",php.version.label="${{ matrix.php-version }}", postgresql.version.label="${{ matrix.pgsql-version }}"'
      - uses: mr-smithers-excellent/docker-build-push@v6.5
        name: Build & push Full matrix of Docker images WITHOUT THEME
        with:
          image: knowpulse/tripalcultivate-base
          tags: notheme-drupal${{ matrix.drupal-version }}-php${{ matrix.php-version }}-pgsql${{ matrix.pgsql-version }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: "drupalversion=${{ matrix.drupal-version }},phpversion=${{ matrix.php-version }},postgresqlversion=${{ matrix.pgsql-version }},installTheme='notheme-'"
          labels: 'drupal.version.label="${{ matrix.drupal-version }}",php.version.label="${{ matrix.php-version }}", postgresql.version.label="${{ matrix.pgsql-version }}"'
      - uses: mr-smithers-excellent/docker-build-push@v6.5
        name: Build baseonly-latest using 11.3.x-dev, PHP 8.5, PgSQL 18
        if: ${{ matrix.drupal-version == '11.3.x-dev' && matrix.php-version == '8.5' && matrix.pgsql-version == '18' }}
        with:
          image: knowpulse/tripalcultivate-base
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: "drupalversion=${{ matrix.drupal-version }},phpversion=${{ matrix.php-version }},postgresqlversion=${{ matrix.pgsql-version }}"
          labels: 'drupal.version.label="${{ matrix.drupal-version }}",php.version.label="${{ matrix.php-version }}", postgresql.version.label="${{ matrix.pgsql-version }}"'
